server:
  port: 9527

spring:
  application:
    name: gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由
      routes:
        - id: payment_route1  # 路由id，唯一
          uri: lb://payment-service  # 路由转发后实际访问地址
          predicates:
            - Path=/payment/getById/**  # 访问地址

        - id: payment_route2
          uri: lb://payment-service
          predicates:
            - Path=/payment/getDiscovery

eureka:
  instance:
    hostname: gateway9527-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
