server:
  port: 80

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411  # zipkin地址
  sleuth:
    sampler:
      probability: 1  # 设置采样率，在0-1之间，1表示全部采集

eureka:
  client:
    #是否把自己注册进EurekaServer，默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认true，单节点无所谓，集群必须为true才能配合Ribbon
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true
