server:
  port: 8802

spring:
  application:
    name: cloud-stream-rabbitmq-consumer
  rabbitmq:
    host: 192.168.10.128
    port: 5672
    username: admin
    password: admin
  cloud:
    stream:
      bindings:  # 服务的整合处理
        input:  # 通道名称
          destination: studyExchange  # 交换机名称
          content-type: application/json  # 设置消息类型为json
          group: test-consumer  # 分组/队列
      binders:  # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:  # 定义的名称，用于和binding整合
          type: rabbit  # 消息组件类型
          environment:  # 设置rabbitmq相关环境信息
            spring:
              rabbitmq:
                host: 192.168.10.128
                port: 5672
                username: admin
                password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2  # 设置心跳间隔时间
    lease-expiration-duration-in-seconds: 5  # 间隔时间
    instance-id: cloud-stream-rabbitmq-consumer-8802  # 在信息列表时显示主机名称
    prefer-ip-address: true  # 访问的路径变为IP地址

